### ISSUE TITLE
install assistance

### ISSUE THREAD

**Issue by N1ck9141** [fepitre/qubes-rofi#1]
hey any advise on getting this to run in dom0, downloaded and copied to dom0 unable to get make file to run?

**Comment by fepitre** [comment]
@N1ck9141: The repo is now integrated into QubesOS-contrib: https://github.com/QubesOS-contrib/qubes-rofi

It's for R4.0 only as Rofi was not available at Fedora 25 times. In order to install it, you need to install first QubesOS-contrib repository (in dom0):

1. sudo qubes-dom0-update qubes-repo-contrib
2. sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4-contrib-fedora
3. Install Rofi: sudo qubes-dom0-update --enablerepo=qubes-contrib-dom0-r4.0-current-testing rofi

There is also `polybar` and `i3-gaps` available. Take a look here: https://github.com/QubesOS-contrib.

@andrewdavidwong, @marmarek: I'm writing this procedure a lot of times, maybe we should do an announcement for QubesOS-contrib?

**Comment by N1ck9141** [comment]
oh I wasnt even aware it had been included that is awesome thank you. Legend

**Comment by andrewdavidwong** [comment]
> @N1ck9141: The repo is now integrated into QubesOS-contrib: https://github.com/QubesOS-contrib/qubes-rofi
> 
> It's for R4.0 only as Rofi was not available at Fedora 25 times. In order to install it, you need to install first QubesOS-contrib repository (in dom0):
> 
> 1. sudo qubes-dom0-update qubes-repo-contrib
> 2. sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-qubes-4-contrib-fedora
> 3. Install Rofi: sudo qubes-dom0-update --enablerepo=qubes-contrib-dom0-r4.0-current-testing rofi
> 
> There is also `polybar` and `i3-gaps` available. Take a look here: https://github.com/QubesOS-contrib.
> 
> @andrewdavidwong, @marmarek: I'm writing this procedure a lot of times, maybe we should do an announcement for QubesOS-contrib?

Perhaps we should add these instructions to the documentation. For example, it could be a new section on the [Installing and updating software in dom0](https://www.qubes-os.org/doc/software-update-dom0/) page.

**Comment by fepitre** [comment]
@andrewdavidwong: Yes indeed. I would suggest that follows a proper official announcement from @marmarek about QubesOS-contrib :)
